### ISSUE TITLE
Clean up for hard-float calling convention

### ISSUE THREAD

**Issue by kito-cheng** [riscv-non-isa/riscv-elf-psabi-doc#268]
Review comment come from @anderslindgren-iar and Anders Berg(IAR) https://lists.riscv.org/g/tech-toolchain-runtime/message/344

> Floating-point registers fs0-fs11 shall be preserved across procedure calls, `provided they hold values no more than FLEN bits wide.`

Anders: Is this comment really needed?

**Comment by jrtc27** [comment]
The point is that the floating-point register names are shared between Zfh, F and D. It could be reworded to be clearer, but it's not redundant information, only the low FLEN bits of floating-point registers are preserved, so you can't store a double in fs0 on RV64IFD LP64F and have it be preserved across calls.

**Comment by kito-cheng** [comment]
> so you can't store a double in fs0 on RV64IFD LP64F and have it be preserved across calls.

The confusion is come from `FLEN`, `FLEN` is 64 in this context, but I guess you mean `FLEN`=32 in this example, so I think we need some term like ABI_FLEN to distinguish that.

**Comment by jrtc27** [comment]
> For the purposes of this section, FLEN refers to the width of a floating-point register in the ABI. The ABI’s FLEN must be no wider than the ISA’s FLEN. The ISA might have wider floating-point registers than the ABI.

Also the Named ABIs section explicitly defines FLEN for each hard-float ABI

**Comment by kito-cheng** [comment]
Oh, yeah, I saw this section, but overriding existing term might not good idea I guess. maybe we could just define ABI_FLEN and update whole section.

> For the purposes of this section, FLEN refers to the width of a floating-point register in the ABI. The ABI’s FLEN must be no wider than the ISA’s FLEN. The ISA might have wider floating-point registers than the ABI.

**Comment by nick-knight** [comment]
> Anders: Is this comment really needed?

I agree with @jrtc27 that it is really needed.

Regarding the following discussion, I don't have issues with the (locally redefined) meaning of FLEN in section [Hardware Floating-point Calling Convention](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#hardware-floating-point-calling-convention). I do think it could be argued that the usage of FLEN in later section [Named ABIs](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#named-abis) is ambiguous because the earlier usage is out of scope. Perhaps an argument could be made that the explicit wording "hardware floating-point calling convention for FLEN=" recalls the earlier usage. In any event, I would support clarifying these later instances. If we do introduce new jargon like ABI_FLEN, I think we should use it consistently throughout the document.
