### ISSUE TITLE
Don't use GCC-specific syntax for example code on psABI

### ISSUE THREAD

**Issue by kito-cheng** [riscv-non-isa/riscv-elf-psabi-doc#270]
Review comment come from @anderslindgren-iar and Anders Berg(IAR) https://lists.riscv.org/g/tech-toolchain-runtime/message/344

```
    # Load value from a symbol
0:  auipc a0, %pcrel_hi(symbol)
    lw    a0, %pcrel_lo(0b)(a0)
    # Store value to a symbol
1:  auipc a0, %pcrel_hi(symbol)
    sw    a1, %pcrel_lo(1b)(a0)
    # Calculate address
2:  auipc a0, %pcrel_hi(symbol)
    addi  a0, a0, %pcrel_lo(2b)
```

Anders: The example is GCC-specific. An example should preferably be tool chain neutral or at least it should be mentioned that it is GCC-specific and that the syntax may differ a bit depending on which toolchain one is using.

**Comment by kito-cheng** [comment]
@anderslindgren-iar I guess I have been living with GNU toolchain for long time, did you mind pointing out which part is GCC-specific syntax, I believe those code could be also compiled with clang but I guess some syntax might not be supported in the IAR compiler? backward Numeric Labels reference or relocation modifier?

**Comment by jrtc27** [comment]
1. GCC doesn't parse assembly, GNU as does
2. This isn't GNU as-specific, this is the standard RISC-V assembly syntax that both GNU as and LLVM agree on
3. There is no alternative syntax, and we're not making up our own, that would be confusing and unhelpful

**Comment by jrtc27** [comment]
(and if IAR decided to come up with their own syntax for their proprietary toolchain then that's IAR's problem)

**Comment by anderslindgren-iar** [comment]
Hi!

Numerical labels and the "b" syntax are not supported by all tools. In 
addition, it's hard to read for users what aren't familiar with the syntax.

In this case, the example would become much clearer if normal, named, 
labels were used.

     -- Anders Lindgren, IAR Systems

Den 2022-04-21 kl. 05:00, skrev Kito Cheng:

**Comment by jrtc27** [comment]
Numeric labels are supported by GNU-compatible assemblers, which both major toolchains have. I do not know of a serious RISC-V assembler that doesn’t support it, and large amounts of real-world code relies on it. If IAR has one that doesn’t that’s your problem and you should support it if you want to be able to build real-world code rather than diverge from the de-facto standard.

Numeric labels are more concise and, importantly, make it clear that the label is for the specific instruction by having it on the same line, rather than for the block if you have it on a separate line as you’d need for a longer text label (unless you use silly amounts of indentation). They also avoid polluting the symbol table.

If someone doesn’t know how numeric labels work then I question whether that portion of the document is aimed at them; we are not targeting an average developer, we are targeting people who are dealing with ABIs. The asm manual is the more user-facing document.
