### ISSUE TITLE
Document should be clear about which ABIs are ratified / proposed for ratification

### ISSUE THREAD

**Issue by asb** [riscv-non-isa/riscv-elf-psabi-doc#312]
I get the impression that ILP32E _isn't_ going to be ratified as part of the [current process](https://discourse.llvm.org/t/risc-v-public-review-for-non-isa-specification-psabi/63822). What about LP64Q?

In both cases (and for any other part of the spec), it would be helpful to be clear - perhaps a status table like the one in the ISA manual?

**Comment by kito-cheng** [comment]
Yes, ILP32E isn't ratified, we've mention that might changed due to ISA isn't ratified[1], but LP64Q is included in this ratification process, that good idea to adding a table to spec! thanks for the suggestion! 

[1] https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#ilp32e-calling-convention
