### ISSUE TITLE
Support Thread-Local Storage Descriptors (TLSDESC)

### ISSUE THREAD

**Issue by MaskRay** [riscv-non-isa/riscv-elf-psabi-doc#94]
TLSDESC (`-mtls-dialect=gnu2`) improves traditional General Dynamic and Local Dynamic TLS models (`-mtls-dialect=gnu`). In the most common case that TLS variables are defined in initially-loaded modules, it simplifies the work in `__tls_get_addr` and (probably more importantly) switches to a custom calling convention that doesn't clobber any register ("preserve any registers they modify"). This speedup is significant.

The linker may relax TLSDESC code sequence to Initial Exec (targeting an executable, the symbol is preemptable) or Local Exec (target an executable, the symbol is non-preemptable) if applicable.

The initial (static) and outstanding (dynamic) relocation types for TLSDESC have to be defined, as well as how static relocation types are relaxed to Initial Exec and Local Exec models.

TLSDESC is currently available on x86, x86-64, arm and aarch64.

x86: https://www.fsfla.org/~lxoliva/writeups/TLS/RFC-TLSDESC-x86.txt
ARM: https://www.fsfla.org/~lxoliva/writeups/TLS/RFC-TLSDESC-ARM.txt (the published paper was referenced by ELF for the Arm 64-bit Architecture (AArch64) and ARM 32-bit)

As I understand it, TLSDESC is a strict improvement, so it might be worth defaulting to TLSDESC and probably deprecating relocation types for General Dynamic/Local Dynamic.

**Comment by aswaterman** [comment]
Seems like a good idea, though a big chunk of work to specify and implement.  Any chance you're volunteering? :)

**Comment by MaskRay** [comment]
I'm still getting my feet wet with riscv toolchain (tracking the progress of musl-riscv, reading `llvm/lib/Target/RISCV` `binutils-gdb/bfd/elf*-riscv.c`, etc)... but I would be happy if I can help. I have some contribution to lld so I may help on the lld (llvm linker) side.

**Comment by richfelker** [comment]
One note based on comments from sorear on `#musl` where this was discussed earlier: since TLSDESC calls have a custom calling convention (usually with few or no clobbers) anyway, it would probably make sense to use a non-default link register for the call. This would avoid the need for the caller to save and restore it.

**Comment by aswaterman** [comment]
Indeed, `t0` is intended for this purpose.

**Comment by rui314** [comment]
It looks like no progress has been made since this was filed, but I'd like to see this to happen. Compared to the current TLS model, TLSDESC is strictly better; it's more generic, more efficient and simpler.

**Comment by aswaterman** [comment]
I don’t think there’s any disagreement on the technical merits. Someone needs to volunteer to do the work.

Many of the folks who work on the toolchain are doing the things their employers think are the most pressing, and this one doesn’t seem to be reaching the top of anyone’s list. So, unless someone volunteers to do it out of the goodness of their hearts, it’ll probably be a few more years.

**Comment by rui314** [comment]
I understand that. I'm currently busy working on my mold linker (which by the way supports RISC-V), so I don't have a bandwidth to take this one, but if someone wants to take this, I'm happy to support.

**Comment by aswaterman** [comment]
@rui314 mold looks like a great project!

**Comment by ishitatsuyuki** [comment]
I'm planning to prototype on an implementation (with draft spec) in the following weeks. I'll keep you updated when I make progress.

**Comment by aswaterman** [comment]
Cool!

**Comment by rui314** [comment]
I'm proud to say that this effort is sponsored by the mold project. We are interested in not only implementing but also improving the RISC-V psABI.

**Comment by ilovepi** [comment]
@rui314 Has there been any progress on this? Are there thing we can do to help?

**Comment by rui314** [comment]
@ishitatsuyuki is working on this.

**Comment by ishitatsuyuki** [comment]
Hi, sorry for the silence, the last few weeks have been a little busy due to IRL matters but I’m still working on this. Currently trying to get a prototype working with the GNU toolchain.

**Comment by ilovepi** [comment]
No need for apologies, open source contributors shouldn't feel pressured to volunteer more time than they already do. So thanks for working on this. 

Are there things we could do to expedite your work? For instance, we could help prototype things on the LLVM side, or help with code review (when ready).  It may also be helpful to sketch out some of the details in this thread, like the set of registers you plan to use (probably just `t0`, `a0`, and _maybe_ a scratch register?) and the new reloc types.

**Comment by kito-cheng** [comment]
@rui314 @ishitatsuyuki really excite to hear you are planing on this!

> Is there any opportunity to use the C (compressed) instruction subset? I didn't find any, but I haven't get myself fully acquainted with the C extension.

IIUC `t0` and `a0` is just a random picked register for current implementation, it could be any pair or registers? if so it would be great to using `a0` and `a1` rather than `t0` and `a0` since `t0` can't be compress-able.

> Should we allow the compiler to interleave the sequence with other instructions? It should be possible to uniquely identify which instruction belongs to which TLS access, by making all but the first relocation to point to label. If so, allowing interleaving gives the compiler a little more opportunity in instruction scheduling.

I would prefer to allow compiler to interleave the sequence if possible, and I am curious, does here benefit if we have fixing code sequence for the linker implementation side?

**Comment by ishitatsuyuki** [comment]
> IIUC `t0` and `a0` is just a random picked register for current implementation, it could be any pair or registers? if so it would be great to using `a0` and `a1` rather than `t0` and `a0` since `t0` can't be compress-able.

`t0` is the alternate link register, and `a0` is the register for the first argument to the function. Using `a1` might be a bit surprising for storing the return address.

Rui suggested that the registers in the instruction sequence is unnecessarily constrained, though, so I'm thinking of relaxing it to something like this:
```
	auipc tX, %tlsdesc_pcrel_hi(symbol)         // R_RISCV_TLSDESC_HI20
	lw    tY, tX, %tlsdesc_pcrel_load_lo(label) // R_RISCV_TLSDESC_LOAD_LO12_I
	addi  a0, tX, %tlsdesc_pcrel_add_lo(label)  // R_RISCV_TLSDESC_ADD_LO12_I
	jalr  t0, tY                                // R_RISCV_TLSDESC_CALL(label)
```
Still, I think *maybe* the instruction sequence for TLSDESC should be kept uncompressed, otherwise this could potentially significantly make relaxation harder by restricting the instructions that it can be replaced with.

> I would prefer to allow compiler to interleave the sequence if possible, and I am curious, does here benefit if we have fixing code sequence for the linker implementation side?

On second thought I think fixing the code sequence is not really necessary, and we probably want to give compiler the freedom of scheduling (and register allocation as mentioned above). So in the draft I'm writing right now I'll go without the scheduling restriction.

---

In other news, I'm currently working on a draft version of spec; it won't be ready for merge until I implement the prototype, but a draft PR should be a better place to discuss this.

**Comment by jrtc27** [comment]
For `jalr t0, tY` you want t0 to be t0 to get the RAS push and you want tY to be anything other than ra; both t0 and some non-link register hint will give you the same hinting.

**Comment by ishitatsuyuki** [comment]
The spec draft is available at https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/373. Let me know about your thoughts.
